include Make.options

.PHONY: default rebuild install clean

default:
	cd src && $(MAKE) default

rebuild:
	cd src && $(MAKE) rebuild

install:
	cd src && $(MAKE) install

clean:
	cd src && $(MAKE) clean
